spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: prod

---

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ttcssendmail@gmail.com
    password: bbkxdvvlcudkygqm
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

application:
  web-client:
    api-key: 660b02a5d4964a7a99930013232007
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

---


